### ISSUE TITLE
Änderungen im Dropdown-Feld haben in Firefox keinen Effekt

### ISSUE THREAD

**Issue by jvoigtlaender** [s6yaschn/LoLApi#5]
In Chrome hingegen schon. Vermutlich ist der Fehler, dass Sie `onInput` verwenden, wo eigentlich `onChange` verwendet werden müsste. (Und Chrome scheint toleranter zu sein und auch das "falsche" Event zu unterstützen.)

http://stackoverflow.com/questions/22563544/oninput-not-working-on-select

**Comment by jvoigtlaender** [comment]
Und vermutlich sollte auch diese Zeile:

https://github.com/s6yaschn/LoLApi/blob/c28638d29d8ea671fcc3696664625ec795e656ec/src/Main.elm#L144

nicht `onInput` verwenden, sondern `onChange`. Machen Sie sich mal über die Unterschiede dieser beiden Events kundig.

**Comment by s6yaschn** [comment]
`onChange` behebt das Problem mit dem Dropdown-Feld, für das Textfeld zur Eingabe führt `onChange` aber dazu, dass erst bei Fokusverlust update aufgerufen wird und erfordert einen unerwarteten Click in einen anderen Bereich der Seite.

Experimentell ist die Seite trotzdem mit `onChange` bei der Key-Eingabe online.`onInput` hat den Nachteil, dass ein sehr großer Overhead von Requests mit unvollständig eingegebenen bzw. daher ungültigen Keys entsteht.
Der beste Kompromiss aus Performance und Clarity sollte ein Form bestehend aus Eingabefeld für den Key und Submit-Button sein.

Ist es richtig, dass `onChange` in keinem Package enthalten ist und als custom event handler umgesetzt werden muss? Ich konnte mir nicht vorstellen, dass zwar Dropdown-Felder, aber nicht der dafür benötigte `onChange` handler verfügbar ist, bin aber leider nicht fündig geworden.

**Comment by jvoigtlaender** [comment]
> `onInput` hat den Nachteil, dass ein sehr großer Overhead von Requests mit unvollständig eingegebenen bzw. daher ungültigen Keys entsteht.
> Der beste Kompromiss aus Performance und Clarity sollte ein Form bestehend aus Eingabefeld für den Key und Submit-Button sein.

Sehe ich auch so. Eine allgemeinere, aber auch aufwändigere, Lösung wäre ein debouncen des Signals. Also erst dann einen Request abzuschicken wenn die Eingabe sich eine gewisse Zeit nicht geändert hat (also etwa wenn der Nutzer aufgehört hat zu tippen). Das wäre unter Elm 0.16 möglich gewesen mit Funktionen wie `settledAfter` aus http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.7.0/Signal-Time. In Elm 0.17 scheint es noch nichts Äquivalentes zu geben, höchstens dies: http://package.elm-lang.org/packages/athanclark/elm-debouncer. Sicher zu aufwändig.

> Ist es richtig, dass `onChange` in keinem Package enthalten ist und als custom event handler umgesetzt werden muss? Ich konnte mir nicht vorstellen, dass zwar Dropdown-Felder, aber nicht der dafür benötigte `onChange` handler verfügbar ist, bin aber leider nicht fündig geworden.

In der Tat merkwürdig. Siehe auch https://github.com/elm-lang/html/issues/23.

**Comment by jvoigtlaender** [comment]
> ... für das Textfeld zur Eingabe führt `onChange` aber dazu, dass erst bei Fokusverlust update aufgerufen wird und erfordert einen unerwarteten Click in einen anderen Bereich der Seite.

Man könnte vermutlich auch was basteln, wo man auf einen Enter-Tastendruck wartet und das als Event zum Abschicken des Requests interpretiert, dafür also auf den Button verzichten könnte. Wäre aber wohl auch irgendwie umständlich...
